//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Parent class for different groupings of information collected and managed as a part of a business process. It will frequently contain references to other objects, such as assets, people and power system resources.
    public class Document : IdentifiedObject {
        
        /// Date and time that this document was created.
        private System.DateTime? cim_createdDateTime;
        
        private const bool isCreatedDateTimeMandatory = false;
        
        private const string _createdDateTimePrefix = "cim";
        
        /// Status of this document. For status of subject matter this document represents (e.g., Agreement, Work), use 'status' attribute.
        ///Example values for 'docStatus.status' are draft, approved, cancelled, etc.
        private Status cim_docStatus;
        
        private const bool isDocStatusMandatory = false;
        
        private const string _docStatusPrefix = "cim";
        
        /// Electronic address.
        private ElectronicAddress cim_electronicAddress;
        
        private const bool isElectronicAddressMandatory = false;
        
        private const string _electronicAddressPrefix = "cim";
        
        /// Date and time this document was last modified. Documents may potentially be modified many times during their lifetime.
        private System.DateTime? cim_lastModifiedDateTime;
        
        private const bool isLastModifiedDateTimeMandatory = true;
        
        private const string _lastModifiedDateTimePrefix = "cim";
        
        /// Revision number for this document.
        private string cim_revisionNumber;
        
        private const bool isRevisionNumberMandatory = true;
        
        private const string _revisionNumberPrefix = "cim";
        
        /// Status of subject matter (e.g., Agreement, Work) this document represents. For status of the document itself, use 'docStatus' attribute.
        private Status cim_status;
        
        private const bool isStatusMandatory = true;
        
        private const string _statusPrefix = "cim";
        
        /// Document subject.
        private string cim_subject;
        
        private const bool isSubjectMandatory = true;
        
        private const string _subjectPrefix = "cim";
        
        /// Document title.
        private string cim_title;
        
        private const bool isTitleMandatory = true;
        
        private const string _titlePrefix = "cim";
        
        /// Utility-specific classification of this document, according to their corporate standards, practices, and existing IT systems (e.g., for management of assets, maintenance, work, outage, customers, etc.).
        private string cim_type;
        
        private const bool isTypeMandatory = true;
        
        private const string _typePrefix = "cim";
        
        public virtual System.DateTime CreatedDateTime {
            get {
                return this.cim_createdDateTime.GetValueOrDefault();
            }
            set {
                this.cim_createdDateTime = value;
            }
        }
        
        public virtual bool CreatedDateTimeHasValue {
            get {
                return this.cim_createdDateTime != null;
            }
        }
        
        public static bool IsCreatedDateTimeMandatory {
            get {
                return isCreatedDateTimeMandatory;
            }
        }
        
        public static string CreatedDateTimePrefix {
            get {
                return _createdDateTimePrefix;
            }
        }
        
        public virtual Status DocStatus {
            get {
                return this.cim_docStatus;
            }
            set {
                this.cim_docStatus = value;
            }
        }
        
        public virtual bool DocStatusHasValue {
            get {
                return this.cim_docStatus != null;
            }
        }
        
        public static bool IsDocStatusMandatory {
            get {
                return isDocStatusMandatory;
            }
        }
        
        public static string DocStatusPrefix {
            get {
                return _docStatusPrefix;
            }
        }
        
        public virtual ElectronicAddress ElectronicAddress {
            get {
                return this.cim_electronicAddress;
            }
            set {
                this.cim_electronicAddress = value;
            }
        }
        
        public virtual bool ElectronicAddressHasValue {
            get {
                return this.cim_electronicAddress != null;
            }
        }
        
        public static bool IsElectronicAddressMandatory {
            get {
                return isElectronicAddressMandatory;
            }
        }
        
        public static string ElectronicAddressPrefix {
            get {
                return _electronicAddressPrefix;
            }
        }
        
        public virtual System.DateTime LastModifiedDateTime {
            get {
                return this.cim_lastModifiedDateTime.GetValueOrDefault();
            }
            set {
                this.cim_lastModifiedDateTime = value;
            }
        }
        
        public virtual bool LastModifiedDateTimeHasValue {
            get {
                return this.cim_lastModifiedDateTime != null;
            }
        }
        
        public static bool IsLastModifiedDateTimeMandatory {
            get {
                return isLastModifiedDateTimeMandatory;
            }
        }
        
        public static string LastModifiedDateTimePrefix {
            get {
                return _lastModifiedDateTimePrefix;
            }
        }
        
        public virtual string RevisionNumber {
            get {
                return this.cim_revisionNumber;
            }
            set {
                this.cim_revisionNumber = value;
            }
        }
        
        public virtual bool RevisionNumberHasValue {
            get {
                return this.cim_revisionNumber != null;
            }
        }
        
        public static bool IsRevisionNumberMandatory {
            get {
                return isRevisionNumberMandatory;
            }
        }
        
        public static string RevisionNumberPrefix {
            get {
                return _revisionNumberPrefix;
            }
        }
        
        public virtual Status Status {
            get {
                return this.cim_status;
            }
            set {
                this.cim_status = value;
            }
        }
        
        public virtual bool StatusHasValue {
            get {
                return this.cim_status != null;
            }
        }
        
        public static bool IsStatusMandatory {
            get {
                return isStatusMandatory;
            }
        }
        
        public static string StatusPrefix {
            get {
                return _statusPrefix;
            }
        }
        
        public virtual string Subject {
            get {
                return this.cim_subject;
            }
            set {
                this.cim_subject = value;
            }
        }
        
        public virtual bool SubjectHasValue {
            get {
                return this.cim_subject != null;
            }
        }
        
        public static bool IsSubjectMandatory {
            get {
                return isSubjectMandatory;
            }
        }
        
        public static string SubjectPrefix {
            get {
                return _subjectPrefix;
            }
        }
        
        public virtual string Title {
            get {
                return this.cim_title;
            }
            set {
                this.cim_title = value;
            }
        }
        
        public virtual bool TitleHasValue {
            get {
                return this.cim_title != null;
            }
        }
        
        public static bool IsTitleMandatory {
            get {
                return isTitleMandatory;
            }
        }
        
        public static string TitlePrefix {
            get {
                return _titlePrefix;
            }
        }
        
        public virtual string Type {
            get {
                return this.cim_type;
            }
            set {
                this.cim_type = value;
            }
        }
        
        public virtual bool TypeHasValue {
            get {
                return this.cim_type != null;
            }
        }
        
        public static bool IsTypeMandatory {
            get {
                return isTypeMandatory;
            }
        }
        
        public static string TypePrefix {
            get {
                return _typePrefix;
            }
        }
    }
}
