//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// Electronic document containing the information necessary to satisfy a given business process set of requirements.
    public class MarketDocument : Document {
        
        private Process cim_Process;
        
        private const bool isProcessMandatory = false;
        
        private const string _ProcessPrefix = "cim";
        
        public virtual Process Process {
            get {
                return this.cim_Process;
            }
            set {
                this.cim_Process = value;
            }
        }
        
        public virtual bool ProcessHasValue {
            get {
                return this.cim_Process != null;
            }
        }
        
        public static bool IsProcessMandatory {
            get {
                return isProcessMandatory;
            }
        }
        
        public static string ProcessPrefix {
            get {
                return _ProcessPrefix;
            }
        }
    }
}
