//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// The location where one or more products are measured. This may be a physical or virtual location.
    public class MeasurementPoint : IdentifiedObject {
        
        private TimeSeries cim_TimeSeries;
        
        private const bool isTimeSeriesMandatory = true;
        
        private const string _TimeSeriesPrefix = "cim";
        
        public virtual TimeSeries TimeSeries {
            get {
                return this.cim_TimeSeries;
            }
            set {
                this.cim_TimeSeries = value;
            }
        }
        
        public virtual bool TimeSeriesHasValue {
            get {
                return this.cim_TimeSeries != null;
            }
        }
        
        public static bool IsTimeSeriesMandatory {
            get {
                return isTimeSeriesMandatory;
            }
        }
        
        public static string TimeSeriesPrefix {
            get {
                return _TimeSeriesPrefix;
            }
        }
    }
}
