//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// An identification of a time interval contaning a set of time points with a given resolution.
    public class Period : IdentifiedObject {
        
        private MarketDocument cim_MarketDocument;
        
        private const bool isMarketDocumentMandatory = false;
        
        private const string _MarketDocumentPrefix = "cim";
        
        /// The number of units of time that compose an individual step within a period.
        private Duration cim_resolution;
        
        private const bool isResolutionMandatory = false;
        
        private const string _resolutionPrefix = "cim";
        
        public virtual MarketDocument MarketDocument {
            get {
                return this.cim_MarketDocument;
            }
            set {
                this.cim_MarketDocument = value;
            }
        }
        
        public virtual bool MarketDocumentHasValue {
            get {
                return this.cim_MarketDocument != null;
            }
        }
        
        public static bool IsMarketDocumentMandatory {
            get {
                return isMarketDocumentMandatory;
            }
        }
        
        public static string MarketDocumentPrefix {
            get {
                return _MarketDocumentPrefix;
            }
        }
        
        public virtual Duration Resolution {
            get {
                return this.cim_resolution;
            }
            set {
                this.cim_resolution = value;
            }
        }
        
        public virtual bool ResolutionHasValue {
            get {
                return this.cim_resolution != null;
            }
        }
        
        public static bool IsResolutionMandatory {
            get {
                return isResolutionMandatory;
            }
        }
        
        public static string ResolutionPrefix {
            get {
                return _resolutionPrefix;
            }
        }
    }
}
