//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// An identification of a set of values beeing adressed within a specific interval of time.
    public class Point : IdentifiedObject {
        
        private Period cim_Period;
        
        private const bool isPeriodMandatory = true;
        
        private const string _PeriodPrefix = "cim";
        
        /// A sequential value representing the relative position within a given time interval.
        private System.Int32? cim_position;
        
        private const bool isPositionMandatory = false;
        
        private const string _positionPrefix = "cim";
        
        public virtual Period Period {
            get {
                return this.cim_Period;
            }
            set {
                this.cim_Period = value;
            }
        }
        
        public virtual bool PeriodHasValue {
            get {
                return this.cim_Period != null;
            }
        }
        
        public static bool IsPeriodMandatory {
            get {
                return isPeriodMandatory;
            }
        }
        
        public static string PeriodPrefix {
            get {
                return _PeriodPrefix;
            }
        }
        
        public virtual int Position {
            get {
                return this.cim_position.GetValueOrDefault();
            }
            set {
                this.cim_position = value;
            }
        }
        
        public virtual bool PositionHasValue {
            get {
                return this.cim_position != null;
            }
        }
        
        public static bool IsPositionMandatory {
            get {
                return isPositionMandatory;
            }
        }
        
        public static string PositionPrefix {
            get {
                return _positionPrefix;
            }
        }
    }
}
