//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// The formal specification of a set of business transactions having the same business goal.
    public class Process : IdentifiedObject {
        
        /// The classification mechanism used to group a set of objects together within a business process. The grouping may be of a detailed or a summary nature.
        private string cim_classificationType;
        
        private const bool isClassificationTypeMandatory = false;
        
        private const string _classificationTypePrefix = "cim";
        
        /// The kind of business process.
        private string cim_processType;
        
        private const bool isProcessTypeMandatory = false;
        
        private const string _processTypePrefix = "cim";
        
        public virtual string ClassificationType {
            get {
                return this.cim_classificationType;
            }
            set {
                this.cim_classificationType = value;
            }
        }
        
        public virtual bool ClassificationTypeHasValue {
            get {
                return this.cim_classificationType != null;
            }
        }
        
        public static bool IsClassificationTypeMandatory {
            get {
                return isClassificationTypeMandatory;
            }
        }
        
        public static string ClassificationTypePrefix {
            get {
                return _classificationTypePrefix;
            }
        }
        
        public virtual string ProcessType {
            get {
                return this.cim_processType;
            }
            set {
                this.cim_processType = value;
            }
        }
        
        public virtual bool ProcessTypeHasValue {
            get {
                return this.cim_processType != null;
            }
        }
        
        public static bool IsProcessTypeMandatory {
            get {
                return isProcessTypeMandatory;
            }
        }
        
        public static string ProcessTypePrefix {
            get {
                return _processTypePrefix;
            }
        }
    }
}
