//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTN {
    using System;
    using FTN;
    
    
    /// A set of regular time-ordered measurements or values of quantitative nature of an individual or collective phenomenon taken at successive, in most cases equidistant, periods / points of time.
    public class TimeSeries : IdentifiedObject {
        
        private MarketDocument cim_MarketDocument;
        
        private const bool isMarketDocumentMandatory = false;
        
        private const string _MarketDocumentPrefix = "cim";
        
        /// Identification of the object that is the common dominator used to aggregate a time series.
        private string cim_objectAggregation;
        
        private const bool isObjectAggregationMandatory = false;
        
        private const string _objectAggregationPrefix = "cim";
        
        private Period cim_Period;
        
        private const bool isPeriodMandatory = true;
        
        private const string _PeriodPrefix = "cim";
        
        /// The type of the product such as Power, energy, reactive power, transport capacity that is the subject of the time series.
        private string cim_product;
        
        private const bool isProductMandatory = false;
        
        private const string _productPrefix = "cim";
        
        /// Version of the time series.
        private string cim_version;
        
        private const bool isVersionMandatory = false;
        
        private const string _versionPrefix = "cim";
        
        public virtual MarketDocument MarketDocument {
            get {
                return this.cim_MarketDocument;
            }
            set {
                this.cim_MarketDocument = value;
            }
        }
        
        public virtual bool MarketDocumentHasValue {
            get {
                return this.cim_MarketDocument != null;
            }
        }
        
        public static bool IsMarketDocumentMandatory {
            get {
                return isMarketDocumentMandatory;
            }
        }
        
        public static string MarketDocumentPrefix {
            get {
                return _MarketDocumentPrefix;
            }
        }
        
        public virtual string ObjectAggregation {
            get {
                return this.cim_objectAggregation;
            }
            set {
                this.cim_objectAggregation = value;
            }
        }
        
        public virtual bool ObjectAggregationHasValue {
            get {
                return this.cim_objectAggregation != null;
            }
        }
        
        public static bool IsObjectAggregationMandatory {
            get {
                return isObjectAggregationMandatory;
            }
        }
        
        public static string ObjectAggregationPrefix {
            get {
                return _objectAggregationPrefix;
            }
        }
        
        public virtual Period Period {
            get {
                return this.cim_Period;
            }
            set {
                this.cim_Period = value;
            }
        }
        
        public virtual bool PeriodHasValue {
            get {
                return this.cim_Period != null;
            }
        }
        
        public static bool IsPeriodMandatory {
            get {
                return isPeriodMandatory;
            }
        }
        
        public static string PeriodPrefix {
            get {
                return _PeriodPrefix;
            }
        }
        
        public virtual string Product {
            get {
                return this.cim_product;
            }
            set {
                this.cim_product = value;
            }
        }
        
        public virtual bool ProductHasValue {
            get {
                return this.cim_product != null;
            }
        }
        
        public static bool IsProductMandatory {
            get {
                return isProductMandatory;
            }
        }
        
        public static string ProductPrefix {
            get {
                return _productPrefix;
            }
        }
        
        public virtual string Version {
            get {
                return this.cim_version;
            }
            set {
                this.cim_version = value;
            }
        }
        
        public virtual bool VersionHasValue {
            get {
                return this.cim_version != null;
            }
        }
        
        public static bool IsVersionMandatory {
            get {
                return isVersionMandatory;
            }
        }
        
        public static string VersionPrefix {
            get {
                return _versionPrefix;
            }
        }
    }
}
